### ISSUE TITLE
Have you checked out FastAPI?

### ISSUE THREAD

**Issue by theholy7** [smoothml/bike-charts#3]
Hey Doc,

Keen to know why you are going with Falcon :)

And joking around with github ahah

Happy Easter

https://github.com/smoothml/bike-charts/blob/03a52495d58cde8d36c36c8ee45c3e675c4119bd/bike_charts/app.py#L1

**Comment by smoothml** [comment]
Because Falcon has the [fastest benchmarks](https://github.com/the-benchmarker/web-frameworks) of any Python web framework. FastAPI would be a good choice too, though.

**Comment by smoothml** [comment]
Ooo, FastAPI auto-generates docs!
